'use client';

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import type { Event, Incident, IncidentListResponse, IncidentDetailResponse, EventListResponse } from '../lib/types';
import { demoEvents, demoIncidents, incidentFromDto, incidentListFromDto } from '../lib/types';
import { useIntegrations, useOperator, useTheme } from '../lib/ui';
import { EmptyState, LoginModal, Sidebar, Topbar } from '../lib/shell';

const statusMeta: Record<string,{label:string; tone:string}> = { DETECTED:{label:'Detected',tone:'amber'}, INVESTIGATING:{label:'Investigating',tone:'blue'}, ACTION_PROPOSED:{label:'Action proposed',tone:'purple'}, AWAITING_APPROVAL:{label:'Awaiting approval',tone:'amber'}, REMEDIATING:{label:'Remediating',tone:'blue'}, VERIFYING:{label:'Verifying',tone:'blue'}, FIX_READY:{label:'Fix ready',tone:'purple'}, RESOLVED:{label:'Resolved',tone:'green'}, ESCALATED:{label:'Escalated',tone:'red'} };

function formatDate(value?: string) { if (!value) return '—'; const d = new Date(value); return Number.isNaN(d.getTime()) ? value : d.toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}); }
function apiErrorMessage(error: unknown) { return error instanceof Error ? error.message : 'The dashboard could not reach the control API.'; }

export default function Dashboard() {
  const preview = typeof window !== 'undefined' && new URLSearchParams(window.location.search).get('preview') === '1';
  const [incidents, setIncidents] = useState<Incident[]>([]);
  const [selected, setSelected] = useState<Incident | null>(null); const [events, setEvents] = useState<Event[]>([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [detailLoading, setDetailLoading] = useState(false);
  const [loginOpen, setLoginOpen] = useState(false); const [actionState, setActionState] = useState<string | null>(null); const [actionPending, setActionPending] = useState(false); const [loginError, setLoginError] = useState<string | null>(null); const [loginEmail, setLoginEmail] = useState(''); const [loginPassword, setLoginPassword] = useState('');
  const [light, toggleTheme] = useTheme();
  const integrations = useIntegrations(preview);
  const { operator, email: operatorEmail, signedIn, signOut } = useOperator();
  const deepLinked = useRef(false);

  const load = useCallback(() => {
    if (preview) return Promise.resolve();
    return Promise.all([fetch('/api/incidents'), fetch('/api/integrations')]).then(async ([ir]) => { if (!ir.ok) throw new Error(`Incidents API returned ${ir.status}`); return [await ir.json()]; }).then(([i]) => { const list = incidentListFromDto(i as IncidentListResponse); setIncidents(list); setSelected(current => current && list.find(item => item.id === current.id) || list[0] || null); setError(null); }).catch(e => setError(apiErrorMessage(e)));
  }, [preview]);

  useEffect(() => { if (preview) { setIncidents(demoIncidents); setSelected(demoIncidents[0]); setEvents(demoEvents); setLoading(false); return; }
    let disposed = false;
    const poll = () => { void load().finally(() => { if (!disposed) setLoading(false); }); };
    poll(); const timer = window.setInterval(poll, 5000); return () => { disposed = true; window.clearInterval(timer); };
  }, [preview, load]);

  useEffect(() => { if (deepLinked.current || preview || loading) return; deepLinked.current = true; const id = new URLSearchParams(window.location.search).get('incident'); if (id) { const match = incidents.find(i => i.id === id); if (match) setSelected(match); } }, [incidents, loading, preview]);

  useEffect(() => { if (!selected || preview) return; let disposed = false; const incidentId = selected.id; const loadDetail = () => { setDetailLoading(true); Promise.all([fetch(`/api/incidents/${incidentId}`), fetch(`/api/incidents/${incidentId}/events`)]).then(async ([dr, er]) => { if (!dr.ok) throw new Error(`Incident API returned ${dr.status}`); if (!er.ok) throw new Error(`Events API returned ${er.status}`); return [await dr.json(), await er.json()]; }).then(([d, ev]) => { if (disposed) return; const incident = incidentFromDto(d as IncidentDetailResponse); const eventData = ev as EventListResponse; if (incident) setSelected(current => current?.id === incidentId ? incident : current); setEvents(Array.isArray(eventData) ? eventData : eventData.events ?? []); }).catch(e => { if (!disposed) setError(apiErrorMessage(e)); }).finally(() => { if (!disposed) setDetailLoading(false); }); }; loadDetail(); const timer = window.setInterval(loadDetail, 5000); return () => { disposed = true; window.clearInterval(timer); }; }, [selected?.id, preview]);

  const counts = useMemo(() => ({ active: incidents.filter(i => !['RESOLVED','ESCALATED'].includes(i.status)).length, verifying: incidents.filter(i => i.status === 'VERIFYING').length, resolved: incidents.filter(i => i.status === 'RESOLVED').length }), [incidents]);
  async function runScenario(scenario: 'prompt_regression'|'tool_contract_regression') { setActionPending(true); setActionState('Working…'); try { const res = await fetch('/api/demo/scenarios', {method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({scenario})}); if (!res.ok) throw new Error(`Scenario API returned ${res.status}`); setActionState(`${scenario === 'prompt_regression' ? 'Prompt' : 'Tool contract'} scenario requested`); } catch (e) { setActionState(apiErrorMessage(e)); } finally { setActionPending(false); } }
  async function resetDemo() { setActionPending(true); setActionState('Resetting…'); try { const res = await fetch('/api/demo/reset', {method:'POST'}); if (!res.ok) throw new Error(`Reset API returned ${res.status}`); setActionState('Demo reset requested'); } catch (e) { setActionState(apiErrorMessage(e)); } finally { setActionPending(false); } }
  async function login(event: React.FormEvent) { event.preventDefault(); setLoginError(null); try { const res = await fetch('/api/auth/login', {method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:loginEmail,password:loginPassword})}); if (!res.ok) throw new Error(res.status === 401 ? 'Invalid operator credentials.' : `Login API returned ${res.status}`); const session = await res.json().catch(() => ({})); signedIn(session.email ?? loginEmail); setLoginOpen(false); setLoginPassword(''); } catch (e) { setLoginError(apiErrorMessage(e)); } }
  function refresh() { setLoading(true); void load().finally(() => setLoading(false)); }

  return <main className="shell">
    <Topbar preview={preview} apiDown={!!error} light={light} onToggleTheme={toggleTheme} operator={operator} operatorEmail={operatorEmail} onSignIn={() => {setLoginError(null);setLoginOpen(true)}} onSignOut={signOut}/>
    <div className="workspace"><Sidebar active="overview" integrations={integrations} operator={operator} activeCount={counts.active}/>
      <section className="content"><div className="page-heading"><div><div className="eyebrow">Operations / Overview</div><h1>Good morning, operator.</h1><p>Watch recovery work across your AI applications.</p></div><button className="secondary-button" onClick={refresh}>↻ <span>Refresh data</span></button></div>
        {error && <div className="notice error"><span>!</span><div><strong>Control API unavailable</strong><p>{error} Check your deployment connection or use <a href="?preview=1">preview mode</a> for the UI fixture.</p></div></div>}
        <div className="metrics"><Metric label="Active incidents" value={loading ? '—' : String(counts.active)} detail={loading ? 'Loading from API' : counts.active ? 'Needs attention' : 'No open incidents'} icon="◉" tone="amber"/><Metric label="In verification" value={loading ? '—' : String(counts.verifying)} detail="Measured live checks" icon="✓" tone="blue"/><Metric label="Resolved" value={loading ? '—' : String(counts.resolved)} detail="Verified recovery only" icon="↗" tone="green"/></div>
        <div className="section-title"><div><h2>Incident queue</h2><p>Durable incidents from the control plane</p></div><div className="section-tools"><span className="last-updated">{loading ? 'Loading…' : preview ? 'Preview fixture · not live' : error ? 'Unavailable · retrying every 5s' : 'Live · polling every 5s'}</span>{operator && <><button className="scenario-button" disabled={actionPending} onClick={() => runScenario('prompt_regression')}>Run prompt regression</button><button className="scenario-button" disabled={actionPending} onClick={() => runScenario('tool_contract_regression')}>Run tool regression</button><button className="reset-button" disabled={actionPending} onClick={resetDemo}>Reset</button></>}</div></div>
        <div className="incident-layout"><div className="incident-list">{loading ? <EmptyState icon="◌" title="Loading incidents" body="Reading the incident store…"/> : error ? <EmptyState icon="!" title="No live data" body="The API did not return an incident list."/> : incidents.length === 0 ? <EmptyState icon="✓" title="No incidents yet" body="When GreenAgain detects a regression, it will appear here."/> : incidents.map(i => <button className={`incident-row ${selected?.id === i.id ? 'selected' : ''}`} key={i.id} onClick={() => { setActionState(null); setSelected(i); }}><div className="row-top"><span className={`status-dot ${statusMeta[i.status]?.tone ?? 'gray'}`}/><span className="incident-name">{i.title ?? i.id}</span><span className={`status-badge ${statusMeta[i.status]?.tone ?? 'gray'}`}>{statusMeta[i.status]?.label ?? i.status}</span></div><div className="row-sub"><span>{i.application ?? 'Unknown application'} · {i.environment ?? 'Unknown environment'}</span><time>{formatDate(i.updatedAt ?? i.createdAt)}</time></div></button>)}</div><div className="detail-card">{selected ? <><div className="detail-header"><div><span className={`status-badge ${statusMeta[selected.status]?.tone ?? 'gray'}`}>{statusMeta[selected.status]?.label ?? selected.status}</span><h2>{selected.title ?? selected.id}</h2><p>{selected.application ?? 'Application unknown'} <span>·</span> {selected.environment ?? 'Environment unknown'}</p></div><button className="more-button">•••</button></div><div className="detail-summary">{selected.summary ?? 'No incident summary has been provided by the control plane.'}</div><div className="detail-facts"><Fact label="Current release" value={selected.release ?? 'Not reported'}/><Fact label="Evidence" value={selected.evidenceCount != null ? `${selected.evidenceCount} items` : 'Not reported'}/><Fact label="Last checked" value={formatDate(selected.updatedAt)}/></div><div className="timeline-heading"><h3>Recovery timeline</h3><span>{detailLoading ? 'Updating…' : `${events.length} events`}</span></div>{events.length === 0 ? <p className="muted">No recovery events recorded yet.</p> : events.map(e => <div className="timeline-item" key={e.id}><span className="timeline-dot"/><div><div className="timeline-top"><strong>{e.type ?? 'Event'}</strong><time>{formatDate(e.createdAt)}</time></div><p>{e.message ?? ''}</p>{e.actor && <small>{e.actor}</small>}</div></div>)}<div className="detail-actions"><button className="primary-button" disabled={actionPending || !operator} onClick={() => runScenario(selected?.category === 'tool_contract_regression' ? 'tool_contract_regression' : 'prompt_regression')}>{operator ? 'Re-run scenario' : 'Sign in to act'}</button><span className="action-state">{actionState ?? (selected.verification?.detail ?? '')}</span></div></> : <EmptyState icon="◌" title="No incident selected" body="Choose an incident from the queue to inspect its recovery timeline."/>}</div></div>
        <div className="footer-note"><span className="shield">♢</span><span><strong>Recovery is measured, not assumed.</strong> GreenAgain only marks an incident resolved after independent verification passes. <a href="#">Read the reliability brief →</a></span></div>
      </section></div>
    <LoginModal open={loginOpen} onClose={() => setLoginOpen(false)} onSubmit={login} email={loginEmail} setEmail={setLoginEmail} password={loginPassword} setPassword={setLoginPassword} error={loginError}/>
  </main>;
}
function Metric({label,value,detail,icon,tone}:{label:string;value:string;detail:string;icon:string;tone:string}) { return <div className="metric"><div className={`metric-icon ${tone}`}>{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div></div> }
function Fact({label,value}:{label:string;value:string}) { return <div><span>{label}</span><strong>{value}</strong></div> }
