/* Synthetic returns support Lambda monitored by GreenAgain. */
export type ReleaseMode = "healthy" | "prompt-regression" | "tool-contract-regression";
export interface Order { id:string; item:string; deliveredAt:string; damaged:boolean; replacementStock:boolean }
export interface ReturnPolicy { id:string; windowDays:number; damagedItemsEligible:boolean; replacementAvailable:boolean }
export interface ToolOutcome { name:string; status:"ok"|"error"; summary:string }
export interface SupportAnswer { decision:"eligible"|"ineligible"|"needs_review"; orderId:string; policyId:string; explanation:string; toolOutcomes:ToolOutcome[] }
export interface InvocationInput { question:string; requestId?:string; source?:"traffic"|"evaluation"; sessionId?:string }
/** Direct Lambda contract used by cloud verification and by the API adapter. */
export interface LambdaInput { message:string; orderId?:string; source?:"traffic"|"evaluation"; sessionId?:string }
export interface LambdaOutput { decision:SupportAnswer["decision"]; orderId:string; policyId:string; explanation:string; toolCalls:ToolOutcome[]; error?:string; releaseId:string; executedVersion:string; traceId?:string }
export interface InvocationResponse { requestId:string; releaseId:string; functionVersion:string; answer:SupportAnswer; traceId?:string }
const ORDERS:Record<string,Order>={"ord-1001":{id:"ord-1001",item:"wireless headphones",deliveredAt:"2026-09-05",damaged:true,replacementStock:true},"ord-1002":{id:"ord-1002",item:"keyboard",deliveredAt:"2026-08-01",damaged:false,replacementStock:true}};
const POLICY:ReturnPolicy={id:"returns-standard-v1",windowDays:30,damagedItemsEligible:true,replacementAvailable:true};
export function releaseMode(v:string|undefined):ReleaseMode{return v==="prompt-regression"||v==="tool-contract-regression"?v:"healthy"}
export function lookupOrder(id:string):Order{const o=ORDERS[id];if(!o)throw new Error(`Order ${id} was not found`);return o}
export function readReturnPolicy():ReturnPolicy{return POLICY}
export function checkReplacementEligibility(o:Order,p:ReturnPolicy):boolean{return o.damaged&&o.replacementStock&&p.damagedItemsEligible&&p.replacementAvailable}
function orderId(q:string):string{const x=q.match(/ord[- ]?\d{4}/i)?.[0]?.toLowerCase().replace(" ","-");return x&&ORDERS[x]?x:/keyboard/i.test(q)?"ord-1002":"ord-1001"}
export function deterministicAnswer(q:string,m:ReleaseMode):SupportAnswer{const id=orderId(q),out:ToolOutcome[]=[];try{const o=lookupOrder(id);out.push({name:"lookup_order",status:"ok",summary:`Found ${o.id}`});if(m==="prompt-regression")return{decision:o.damaged?"eligible":"ineligible",orderId:id,policyId:"",explanation:"The item appears eligible based on order details.",toolOutcomes:out};const p=readReturnPolicy();out.push({name:"read_return_policy",status:"ok",summary:`Applied ${p.id}`});if(m==="tool-contract-regression"){out.push({name:"check_replacement_eligibility",status:"error",summary:"Tool response did not contain the expected order.status field"});throw new Error("Tool contract mismatch: expected order.status")}const ok=checkReplacementEligibility(o,p);out.push({name:"check_replacement_eligibility",status:"ok",summary:ok?"Replacement is available":"Replacement is unavailable"});return{decision:ok?"eligible":"ineligible",orderId:id,policyId:p.id,explanation:ok?"The damaged item is within the return policy and a replacement is in stock.":"The order does not meet the replacement policy.",toolOutcomes:out}}catch(e){out.push({name:"support_agent",status:"error",summary:e instanceof Error?e.message:"Unknown tool failure"});return{decision:"needs_review",orderId:id,policyId:POLICY.id,explanation:"The request could not be completed because a required tool failed.",toolOutcomes:out}}}
function valid(v:unknown):v is SupportAnswer{if(!v||typeof v!=="object")return false;const c=v as Record<string,unknown>;return ["eligible","ineligible","needs_review"].includes(String(c.decision))&&typeof c.orderId==="string"&&typeof c.policyId==="string"&&typeof c.explanation==="string"&&Array.isArray(c.toolOutcomes)}
async function openAi(q:string,model:string):Promise<SupportAnswer>{const key=process.env.OPENAI_API_KEY;if(!key)throw new Error("OPENAI_API_KEY is not configured");const r=await fetch("https://api.openai.com/v1/chat/completions",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${key}`},body:JSON.stringify({model,temperature:0,messages:[{role:"system",content:"You are a returns support agent. Use synthetic tools and return only JSON with decision, orderId, policyId, explanation, toolOutcomes. Never invent policy identifiers."},{role:"user",content:q}],response_format:{type:"json_object"}})});if(!r.ok)throw new Error(`Model request failed with status ${r.status}`);const p=await r.json() as{choices?:{message?:{content?:string}}[]};const s=p.choices?.[0]?.message?.content;if(!s)throw new Error("Model returned no structured content");const v:unknown=JSON.parse(s);if(!valid(v))throw new Error("Model returned an invalid support answer");return v}
interface Trace{ id:string; finish:(output:unknown,error?:string)=>Promise<void> }
function id():string{return globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random().toString(16).slice(2)}`}
async function trace(input:InvocationInput,releaseId:string,version:string,env:NodeJS.ProcessEnv=process.env):Promise<Trace|undefined>{const key=env.LANGSMITH_API_KEY;if(!key||env.LANGSMITH_TRACING==="false")return;const runId=id(),base=(env.LANGSMITH_ENDPOINT||"https://api.smith.langchain.com").replace(/\/$/,"");const run={id:runId,name:"greenagain-monitored-support-agent",run_type:"chain",inputs:{question:input.question},start_time:Date.now(),project_name:env.LANGSMITH_PROJECT||"greenagain-monitored-agent",tags:["greenagain","monitored-agent",input.source||"traffic"],extra:{metadata:{app:"greenagain-demo-support",environment:env.NODE_ENV||"production",releaseId,functionVersion:version,commitSha:env.COMMIT_SHA||"unknown",promptVersion:env.PROMPT_VERSION||"unknown",source:input.source||"traffic"}}};const r=await fetch(`${base}/runs`,{method:"POST",headers:{"content-type":"application/json","x-api-key":key},body:JSON.stringify(run)});if(!r.ok)throw new Error(`LangSmith trace start failed with status ${r.status}`);return{id:runId,finish:async(output,error)=>{const done=await fetch(`${base}/runs/${runId}`,{method:"PATCH",headers:{"content-type":"application/json","x-api-key":key},body:JSON.stringify({outputs:error?undefined:output,error,end_time:Date.now()})});if(!done.ok)throw new Error(`LangSmith trace completion failed with status ${done.status}`)}}}
export async function invoke(input:InvocationInput,env:NodeJS.ProcessEnv=process.env):Promise<InvocationResponse>{const m=releaseMode(env.DEMO_RELEASE_MODE),releaseId=env.RELEASE_ID||env.DEMO_RELEASE_ID||`demo-${m}`,version=env.AWS_LAMBDA_FUNCTION_VERSION||env.DEMO_FUNCTION_VERSION||"$LATEST",requestId=input.requestId||id(),t=await trace(input,releaseId,version,env);try{let answer:SupportAnswer;if(m==="healthy"&&env.OPENAI_API_KEY&&env.OPENAI_MODEL){try{answer=await openAi(input.question,env.OPENAI_MODEL)}catch{answer=deterministicAnswer(input.question,m)}}else answer=deterministicAnswer(input.question,m);const result={requestId,releaseId,functionVersion:version,answer,...(t?{traceId:t.id}: {})};if(t)await t.finish(result);return result}catch(e){if(t)await t.finish(undefined,e instanceof Error?e.message:"Invocation failed");throw e}}
export function criticalCheck(answer:SupportAnswer):{pass:boolean;reason?:string}{if(!answer.orderId||!answer.policyId||answer.decision==="needs_review")return{pass:false,reason:"missing required decision evidence"};if(!answer.toolOutcomes.some(x=>x.name==="read_return_policy"&&x.status==="ok"))return{pass:false,reason:"return policy was not consulted"};return{pass:true}}
export async function supportHandler(input:LambdaInput,env:NodeJS.ProcessEnv=process.env):Promise<LambdaOutput>{const normalized:InvocationInput={question:input.orderId?`${input.message} (order ${input.orderId})`:input.message,source:input.source,sessionId:input.sessionId};try{const r=await invoke(normalized,env);return{decision:r.answer.decision,orderId:r.answer.orderId,policyId:r.answer.policyId,explanation:r.answer.explanation,toolCalls:r.answer.toolOutcomes,releaseId:r.releaseId,executedVersion:r.functionVersion,...(r.traceId?{traceId:r.traceId}:{})}}catch(e){return{decision:"needs_review",orderId:input.orderId||"unknown",policyId:"",explanation:"The support agent failed before completing the request.",toolCalls:[],error:e instanceof Error?e.message:"internal error",releaseId:env.RELEASE_ID||"unknown",executedVersion:env.AWS_LAMBDA_FUNCTION_VERSION||"$LATEST"}}}
export async function handler(event:{body?:string|null;requestContext?:{requestId?:string}}):Promise<{statusCode:number;headers:Record<string,string>;body:string}>{try{const b=event.body?JSON.parse(event.body)as Partial<InvocationInput>:{};if(typeof b.question!=="string"||!b.question.trim())return{statusCode:400,headers:{"content-type":"application/json"},body:JSON.stringify({error:"question is required"})};const r=await invoke({question:b.question,requestId:b.requestId||event.requestContext?.requestId,source:b.source==="evaluation"?"evaluation":"traffic"});return{statusCode:200,headers:{"content-type":"application/json"},body:JSON.stringify(r)}}catch(e){return{statusCode:500,headers:{"content-type":"application/json"},body:JSON.stringify({error:e instanceof Error?e.message:"internal error"})}}}
